language: node_js
node_js:
  - 8
before_script:
  - npm install
script: npm run build
deploy:
  local-dir: www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
